[[redirects]]
from = "/episodes/0"
to = "/podcast/episode/00-developer-fangen-bei-0-an-zu-zählen?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/1"
to = "/podcast/episode/01-side-projects-fluch-oder-segen-für-die-karriere?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/2"
to = "/podcast/episode/02-technologienzoo-side-projects?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/3"
to = "/podcast/episode/03-over-engineering-das-werkzeug-des-teufels?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/4"
to = "podcast/episode/04-lohnt-der-einstieg-in-open-source?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/5"
to = "/podcast/episode/05-team-lead-der-einzige-ausweg?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/6"
to = "/podcast/episode/06-hype-oder-hope-job-titel-und-beförderungen?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/7"
to = "/podcast/episode/07-die-freelance-freiheit?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/8"
to = "/podcast/episode/08-vergiss-doch-datenbanken?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/9"
to = "/podcast/episode/09-ukraine?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/10"
to = "/podcast/episode/10-das-karriere-booster-meeting-11s?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/11"
to = "/podcast/episode/11-die-suche-nach-dem-it-traumjob?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/12"
to = "/podcast/episode/12-make-oder-buy?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/13"
to = "/podcast/episode/13-produktivität?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/14"
to = "/podcast/episode/14-async-und-await-asynchrones-arbeiten-im-alltag?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/15"
to = "/podcast/episode/15-source-code-kommentare-git-commits-messages-merge-commits-und-branch-visualisierungs-kunst?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/16"
to = "/podcast/episode/16-code-reviews-nützlich-oder-bremsen-nur-ein-gutes-team?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/17"
to = "/podcast/episode/17-was-können-wir-beim-incident-management-von-der-feuerwehr-lernen?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/18"
to = "/podcast/episode/18-ziele-und-performance-metriken-für-teams-und-mich-selbst?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/19"
to = "/podcast/episode/19-datenbank-deepdive-oder-das-ende-einer-ära-von-redis-bis-clickhouse?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/20"
to = "/podcast/episode/20-off-boarding-und-on-boarding-wie-verlasse-ich-eine-firma-richtig?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/21"
to = "/podcast/episode/21-static-site-generators-die-webseite?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/22"
to = "/podcast/episode/22-nosql-acid-base-ende-einer-ära-teil-2?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/23"
to = "/podcast/episode/23-schaltest-du-noch-oder-automatisiert-du-schon-home-automation?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/24"
to = "/podcast/episode/24-infrastructure-as-code-oder-old-man-yells-at-cloud?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/podcast/rss"
to = "https://feeds.redcircle.com/0ecfdfd7-fda1-4c3d-9515-476727f9df5e"
status = 302
force = true

[[redirects]]
from = "/episodes/25"
to = "/podcast/episode/25-tech-entlassungswellen-job-interview-skills?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/26"
to = "/podcast/episode/26-my-english-is-not-the-yellow-from-the-egg-arbeiten-in-internationalen-teams?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/27"
to = "/podcast/episode/27-sicherheit-in-der-dependency-hölle?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/28"
to = "/podcast/episode/28-o1-olog-n-on2-ist-die-komplexität-von-algorithmen-im-entwickler-alltag-relevant?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/29"
to = "/podcast/episode/29-die-andere-seite-meetups-konferenzen-organisieren?pk_campaign=shortlink"
status = 301
force = true

[[redirects]]
from = "/episodes/30"
to = "/podcast/episode/30-ist-ein-informatikstudium-sinnvoll-welche-ausbildung-für-devs?pk_campaign=shortlink"
status = 301
force = true

[build]
publish = "dist/"
command = "astro build"
