name: Astro testing

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '5 1 * * *' # Run nightly
  workflow_dispatch:

jobs:
  astro-testing:
    name: Astro build
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.17.0

      - name: Run make clean
        run: make clean

      - name: Run make init-javascript
        run: make init-javascript

      - name: Run make build
        run: make build
