name: JavaScript testing

on:
  push:
    branches:
      - main
    paths:
      - 'src/**/*.js'
      - 'src/**/*.ts'
      - 'src/**/*.astro'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    paths:
      - 'src/**/*.js'
      - 'src/**/*.ts'
      - 'src/**/*.astro'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

jobs:
  testing:
    name: Testing (JavaScript)
    runs-on: ubuntu-26.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          node-version: 24.21.0

      - name: Install dependencies
        run: make init-javascript

      - name: Run unit tests
        run: make test-javascript
