name: Publish Podcast Episodes

on:
  schedule:
    - cron: "0 4 * * 2" # At 04:00 on Tuesday (UTC) or 6:00 in Vienna but seems that there is a lot of cron traffic, usually it is executed between 7 and 8
  workflow_dispatch:

jobs:
  publishing:
    name: Sync and update podcast episodes
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: 'scripts/.python-version'
          cache: 'pip'

      - name: Install python dependencies
        run: pip install -r scripts/requirements.txt

      - name: Run make update-content
        run: make update-content
        env:
          SPOTIFY_APP_CLIENT_ID: ${{ secrets.SPOTIFY_APP_CLIENT_ID }}
          SPOTIFY_APP_CLIENT_SECRET: ${{ secrets.SPOTIFY_APP_CLIENT_SECRET }}

      - name: Run make update-redirects
        run: make update-redirects

      # Commit results back to repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Synchronisation of Podcast Episodes and redirects
          branch: main
          commit_user_name: Podcast synchronisation workflow bot
          commit_user_email: stehtisch@engineeringkiosk.dev
          commit_author: Podcast synchronisation workflow bot <stehtisch@engineeringkiosk.dev>
