name: Python linting (ruff)

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '5 1 * * *' # Run nightly
  workflow_dispatch:

jobs:
  ruff:
    name: Python linting (ruff)
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5.0.0
      - uses: actions/setup-python@v5.6.0
        with:
          python-version-file: 'scripts/.python-version'
          cache: 'pip'

      - name: Install ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff
        run: ruff check --output-format=github scripts/
