name: Python script testing

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "5 1 * * *" # Run nightly
  workflow_dispatch:

jobs:
  python-testing:
    name: pytest
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: ./scripts

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: 'scripts/.python-version'
          cache: 'pip'

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Run make tests
        run: make tests
